import {useEffect,useState} from "react";import Photo from "./Photo";import "./Hero.css";
const dishes=[
{name:"Smoky Jollof Chicken",price:"6,500",was:"7,500",blurb:"Party-style jollof, smoky grilled chicken, fried plantain and a bright house pepper sauce.",image:"https://images.unsplash.com/photo-1603133872878-684f208fb84b?auto=format&fit=crop&w=1000&q=85"},
{name:"Suya Beef Bowl",price:"7,200",was:"8,000",blurb:"Tender suya-spiced beef with seasoned rice, crisp slaw, greens and our creamy pepper dressing.",image:"https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1000&q=85"},
{name:"Crispy Chicken Stack",price:"6,800",was:"7,800",blurb:"Crunchy chicken, fresh slaw, tomato and a smoky mayo tucked into a toasted bun.",image:"https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=1000&q=85"},
{name:"Green Market Bowl",price:"5,900",was:"6,500",blurb:"Seasonal greens, roasted vegetables, grains, avocado and a sharp citrus dressing.",image:"https://images.unsplash.com/photo-1512621776951-a57141f2eefd?auto=format&fit=crop&w=1000&q=85"},
{name:"Creamy Pesto Pasta",price:"6,200",was:"7,000",blurb:"Silky pesto pasta, roasted tomatoes, parmesan and fresh basil for an easy comfort meal.",image:"https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1000&q=85"},
{name:"Berry Cream Cup",price:"3,500",was:"4,000",blurb:"Vanilla cream, fresh berries, crunchy crumble and a little berry sauce to finish.",image:"https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1000&q=85"}];
const DEAL_MS=3*24*60*60*1000;function useCountdown(){const[end]=useState(()=>Date.now()+DEAL_MS);const[left,setLeft]=useState(DEAL_MS);useEffect(()=>{const id=setInterval(()=>setLeft(Math.max(0,end-Date.now())),30000);return()=>clearInterval(id)},[end]);const mins=Math.floor(left/60000);return{days:Math.floor(mins/1440),hours:Math.floor(mins%1440/60),minutes:mins%60}}
export default function Hero({onNavigate}){const[i,setI]=useState(0);const item=dishes[i];const{days,hours,minutes}=useCountdown();const prev=()=>setI((i-1+dishes.length)%dishes.length);const next=()=>setI((i+1)%dishes.length);return <header className="hero" id="top"><div className="hero__left"><div className="hero__eyebrow"><span/> Dave's pick of the day</div><h1 className="hero__title">{item.name}</h1><p className="hero__rating"><span>★★★★★</span>{" "}<a href="#reviews" onClick={e=>{if(onNavigate){e.preventDefault();onNavigate("reviews")}}}>4.9 from 128 reviews</a></p><p className="hero__blurb">{item.blurb}</p><div className="hero__buy"><a href="#order" className="btn">Order this <span>↗</span></a><p className="hero__price"><s>₦{item.was}</s>₦{item.price}</p></div><ul className="hero__thumbs">{dishes.map((dish,n)=><li key={dish.name}><button className={n===i?"is-active":""} onClick={()=>setI(n)}>{String(n+1).padStart(2,"0")}</button></li>)}</ul></div><div className="hero__right"><div className="hero__shape"/><div className="hero__clock"><span>Weekend special</span><div><b>{String(days).padStart(2,"0")}</b><small>days</small></div><div><b>{String(hours).padStart(2,"0")}</b><small>hrs</small></div><div><b>{String(minutes).padStart(2,"0")}</b><small>min</small></div></div><div className="hero__photo"><Photo src={item.image} alt={item.name}/></div><div className="hero__arrows"><button onClick={prev}>←</button><button onClick={next}>→</button></div></div></header>}